### PR TITLE
docs: the keymap's two matchers, and the key names a hand-edited file is read against

### PR DESCRIPTION
**Pull request by arjun28115**
Document the AWT interceptor and Compose matcher, accepted key-name aliases, platform rendering differences and troubleshooting for hand-edited keymaps.

@arjun28115 authored the original documentation. Agent corrections distinguish the static Shortcuts tester from the actual Compose matcher, clarify which table cells contain preset spellings, avoid claiming all preset names are literal Compose property names, and qualify legacy numeric-key guidance for builds with the #335 repair.

This documentation PR stays separate and targets dev. It does not implement the fixes in #373/#335/#376 and is not a duplicate of them. Source review and git diff --check passed. Original head had green platform/code-quality checks and skipped Claude; final-head CI is awaiting fork approval. No UI behavior or app instances were changed.

All four factual review findings were addressed in e9eade957: version-qualified re-recording advice, legacy capture as a numeric producer, accurate preset aliases, and old tester false-failure caveats. The alias test link and single-spelling examples were added. Source review and diff checks pass; runtime changes are separately verified in the #376 integrated stack (257 tests and root quality gates).

Integrated dev `51ee90830` after #305 landed concurrently. The capture round-trip test now includes the new D preset binding; the 257-test run includes ChromeDensityControlsTest. #374 and #405 are closed with contributor-credit consolidation comments. No PR merged.

### CODE REVIEW

**Comment by kshivang** [comment]
@claude review the current head, including compatibility with the other keymap PRs (#373, #335, #376). Original heads had no completed Claude review. Please review only; do not merge.

**Comment by kshivang** [comment]
Addressed all four main documentation findings: manual name replacement comes first, re-recording is qualified to fixed builds, legacy numeric capture is named explicitly, Spacebar is first and preset-vocabulary guidance is qualified, and old tester false failures are documented. Added single-spelling examples, Zero/literal-space aliases, the CanonicalKeyNameTest link and the double-shift-before-modifier-gate clarification. Runtime PRs do not edit this document, so there is no textual conflict with #373/#335/#376. git diff --check passes. No merge performed.
